### PR TITLE
Porting swift mime to Swift3

### PR DESCRIPTION
**Pull request by jlnquere**
Hi, 

I've made a straight forward port of SwiftMime to Swift3. I think it would be a good idea to create a dedicated branch for it.

### CODE REVIEW

**Comment by weekwood** [comment]
Thanks, let me check and merge it

**Comment by jlnquere** [comment]
Hello, any update on this ? :)

**Comment by weekwood** [comment]
@juli1quere Thanks your help, I create 1.0.0 with some break changes finally.

**Comment by jlnquere** [comment]
Good news 👍

**Pull request merged**
